project:
  type: website

website:
  title: "EpiForecasts"
  site-url: https://epiforecasts.io
  repo-url: https://github.com/epiforecasts/epiforecasts.github.io
  twitter-card: 
    site: "@epiforecasts"
  repo-actions: [edit, source]
  description: "EpiForecasts team website"
  comments:
    giscus:
      repo: epiforecasts/epiforecasts.github.io
      category: 'Website discussions'
      mapping: title
      reactions-enabled: true
  navbar:
    left:
      - text: "People"
        href: people.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Software"
        href: software.qmd
      - text: "Publications"
        href: pubs.qmd
    right:
      - icon: github
        href: https://github.com/epiforecasts/

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
