project:
  type: website

website:
  title: "EpiForecasts"
  site-url: https://epiforecasts.io
  repo-url: https://github.com/epiforecasts/epiforecasts.github.io
  body-header: '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.7.0/css/academicons.min.css" integrity="sha512-GGGNUPDhnG8LEAEDsjqYIQns+Gu8RBs4j5XGlxl7UfRaZBhCCm5jenJkeJL8uPuOXGqgl8/H1gjlWQDRjd3cUQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />'
  body-footer: '<script data-goatcounter="https://epiforecasts.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>'
  twitter-card: 
    site: "@epiforecasts"
  repo-actions: [edit, source]
  description: "EpiForecasts team website"
  navbar:
    left:
      - text: "People"
        href: people.qmd
      - text: "Lab manual"
        href: lab-manual.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Software"
        href: software.qmd
      - text: "Publications"
        href: pubs.qmd
      - text: "Join us"
        href: positions.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/epiforecasts/

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
